#!/bin/sh
# *******************************************************************************
# Copyright (C) Altera Corporation
#
# This code and the related documents are Altera copyrighted materials and your
# use of them is governed by the express license under which they were provided to
# you ("License"). This code and the related documents are provided as is, with no
# express or implied warranties other than those that are expressly stated in the 
# License.
# *******************************************************************************/

### BEGIN INIT INFO
# Provides:          local-scripts
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: run scripts in /etc/local.d
### END INIT INFO

. /etc/init.d/functions

test -x $DAEMON_PATH || exit 0

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

RETVAL=0
SCRIPT_LOCATION="/etc/local.d"

case "$1" in                                                                            
    start)                                                                              
	for script in ${SCRIPT_LOCATION}/*
	do
		sh $script start
	done
        ;;                                                                              
                                                                                        
    stop)                                                                               
	for script in ${SCRIPT_LOCATION}/*
	do
		sh $script stop
	done
        ;;                                                                              
                                                                                        
    restart)                                                                            
	for script in ${SCRIPT_LOCATION}/*
	do
		sh $script restart
	done
	;;

    *)
	echo "Usage: $0 { start | stop | restart }"
	;;
esac
