#!/bin/sh
# *******************************************************************************
# Copyright (C) Altera Corporation
#
# This code and the related documents are Altera copyrighted materials and your
# use of them is governed by the express license under which they were provided to
# you ("License"). This code and the related documents are provided as is, with no
# express or implied warranties other than those that are expressly stated in the 
# License.
# *******************************************************************************/


MODULES_LOAD="OmniTekFPGABus OT_HC_OmniTek OT_HC_LocalFPGA OT_Cap_EyeScanDMA OT_Cap_FPGA OT_Cap_MDMA OT_Cap_MemMapBar OT_Cap_OmniFB OT_Cap_VideoFDMA OT_Cap_RegisterAccess"
MODULES_UNLOAD="OT_Cap_RegisterAccess OT_Cap_VideoFDMA OT_Cap_OmniFB OT_Cap_MemMapBar OT_Cap_MDMA OT_Cap_FPGA OT_Cap_EyeScanDMA OT_HC_LocalFPGA OT_HC_OmniTek OmniTekFPGABus"

start ()
{
	for i in ${MODULES_LOAD}
	do
		modprobe $i
	done
}

stop ()
{
	for i in ${MODULES_UNLOAD}
	do
		rmmod $i 2>/dev/null
	done
}

restart ()
{
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

